Move collector logic from main to separate package
google/dnsmasq_exporter pull request #26
Opened 2023-06-12 09:27 UTC by marctc

This PR moves all logic of the collector to a separate package. This is useful to make
this exporter a importable as a library. This is needed for projects like Grafana Agent which
embeds [dnsmasq as prometheus exporter.](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.dnsmasq/)

2023-06-14 18:38 UTC, stapelberg commented
I don’t mind the logic move, but can you remove the switch to go-kit/logging please? I don’t think we should depend on a specific logging library now that the https://tip.golang.org/doc/go1.21#slog package is around the corner with the upcoming go1.21.

2023-06-15 10:48 UTC, marctc commented
> I don’t mind the logic move, but can you remove the switch to go-kit/logging please? I don’t think we should depend on a specific logging library now that the https://tip.golang.org/doc/go1.21#slog package is around the corner with the upcoming go1.21.

Done, thanks for the input!

2023-06-16 06:36 UTC, stapelberg requested changes

2023-06-16 06:36 UTC, stapelberg commented on collector/collector.go
Please keep the copyright note at the top of each file

2023-06-16 06:36 UTC, stapelberg commented on collector/collector.go
> +func New(client *dns.Client, dnsmasqAddr string, leasesPath string, exposeLeases bool) *Collector {
Can we use an option struct here instead of parameters? I imagine that aside from the required parameters, we might grow more optional ones (like exposeLeases) over time, and we can’t just add more function arguments easily (but we can add more struct fields).

2023-06-19 21:40 UTC, stapelberg approved these changes

2023-06-19 21:42 UTC, stapelberg commented
Tests are failing on GitHub Actions. Can you get them to pass please?

2023-06-20 09:34 UTC, marctc commented
> Tests are failing on GitHub Actions. Can you get them to pass please?

I can't run the GitHub Action. I tried locally and it worked.

2023-06-20 10:00 UTC, merged

2023-06-20 10:00 UTC, stapelberg commented
Thanks for your contribution!

2023-06-20 10:02 UTC, marctc commented
> Thanks for your contribution!

thanks!